---

  - debug: var="cert_config"

  - name: LetsEncrypt | template domain registration script
    template:
      src: templates/issue_cert.sh.j2
      dest: /tmp/issue_cert.sh
      mode: "u=rwx,g=rx,o=rx"
    tags:
      - letsencrypt

  - name: LetsEncrypt | execute issue certs script
    command: /tmp/issue_cert.sh
    register: reg_result
    ignore_errors: true
    changed_when: False
    become: yes
    become_user: le
    tags:
      - letsencrypt

  - debug: var="reg_result"

  - block:
      - block:

          - name: LetsEncrypt | Ensure ssl_install_path dir exists
            file: path="{{ cert_config["ssl_install_path"] }}" state="directory" owner="le" group="root" mode="u=rwx,g=rwx,o="
            become: yes
            tags:
              - letsencrypt

          - name: LetsEncrypt | detect primary domain
            set_fact:
              cert_primary_domain: "{{ cert_config['names'][0] }}"
              cert_primary_name: "{{ cert_config['certname'] if ('certname' in cert_config) else cert_config['names'][0] }}"

          - name: LetsEncrypt | template certificates installation script
            template:
              src: templates/install_cert.sh.j2
              dest: /tmp/install_cert.sh
              mode: "u=rwx,g=rx,o=rx"
            tags:
              - letsencrypt

          - name: LetsEncrypt | execute cert installation script
            command: /tmp/install_cert.sh
            register: reg_result
            ignore_errors: true
            become: yes
            become_user: le
            tags:
              - letsencrypt

        when: ("scheme" not in cert_config) or (cert_config["scheme"] == "key_crt")

    when: cert_config.ssl_install_path is defined
